inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false
